spring.datasource.url=jdbc:mysql://localhost:3306/zteypszw_savevege?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
spring.datasource.username=zteypszw_savevege
spring.datasource.password=Pj26022568.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080

