# ใช้ PORT ของ Railway
server.port=${PORT:8080}

# อ่านค่าจาก Railway Variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate Dialect (เลือกของ MySQL รุ่นใหม่)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ให้ Hibernate จัดการสร้าง/อัปเดตตารางอัตโนมัติ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.datasource.url=jdbc:mysql://localhost:3306/orgv?useSSL=false&serverTimezone=Asia/Bangkok&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=root
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# server.port=8081